### ISSUE TITLE
Describe the process for modifying a regex

### ISSUE THREAD

**Issue by NilsEnevoldsen** [vincentarelbundock/countrycode#220]
Could you describe the process for modifying a regex? I thought it would be something like this:

1. modify data_static.csv regex
2. modify data_panel.csv regex
3. run build_panel.R
4. run build.R
5. check the package with devtools

But this doesn't work because the build scripts left_join data from backup.rds using country.name.en.regex, which fails because country.name.en.regex backup.rds wasn't changed.

**Comment by vincentarelbundock** [comment]
Not sure why it doesn't work on your computer. I tried this in my mac terminal and it seemed to work:

```
git clone https://github.com/vincentarelbundock/countrycode
cd countrycode
gsed -i 's/^Afghanistan,afghan/Afghanistan,junk/' "dictionary/data_static.csv"
Rscript dictionary/build.R
Rscript -e "devtools::install();countrycode::codelist[1:4, 1:6]"
```

Which outputs this with the "correct" version of the "junk" regex instead of "afghan".

```r
       ar5 continent country.name.de country.name.de.regex country.name.en
1     ASIA      Asia     Afghanistan                afghan     Afghanistan
2 OECD1990    Europe   Aland Islands                 åland   Åland Islands
3      EIT    Europe        Albanien              albanien         Albania
4      MAF    Africa        Algerien              algerien         Algeria
  country.name.en.regex
1                  junk
2                 åland
3               albania
4               algeria
```

Obviously, this only modifies the main dictionary. Panel has to

**Comment by vincentarelbundock** [comment]
BTW, I don't like our current process of building the panel and the main dict separately. This should be a single script IMO. Will look into streamlining it now.

**Comment by NilsEnevoldsen** [comment]
Try those commands again, but this time do
```
countrycode::codelist[1, 1:35]
```
and you'll see the problem. :-)

**Comment by NilsEnevoldsen** [comment]
BTW, Vincent, I'm using Sigman and Hanson for something, and was happy to see your method referenced.

**Comment by vincentarelbundock** [comment]
Arrrgh! I see the problem. Our build code is absolutely terrible (my fault). I'm doing a serious re-factor now and should be able to publish it over the weekend or early next week. Sorry for the delay.

Oh, interesting about Sigman and Hanson! TBH, the model never worked too well in the context of our specific application. We had lots of NMAR missingness and our strategy for dealing with it didn't quite cut it. For this reason (and others), we never tried to publish it, even if the model did have some cool features. Nice to see that other folks are working to improve it!

**Comment by vincentarelbundock** [comment]
I pushed a major refactor of the dictionary build code to master. @NilsEnevoldsen, if you want to change a regex, you should:

1. modify `dictionary/data_static.csv`
2. run `dictionary/build.R`

In principle, that should take care of both the cross-section and the panel code lists.

@cjyetman here are some changes you might want to be aware of:

* Created `get_polity4.R`, `get_cow.R`, `get_vdem.R`, `get_small_countries.R`
* Removed `build_panel.R`
* Cross-section versions of the panel variables are now created automatically by taking the latest non-missing value. That's all done in `build.R`.
* Created `test-codelist.R`

I'm reasonably confident that this works, but it's an important change to a critical part of the codebase, so I'll be dog-fooding it for a while before releasing to CRAN.

**Comment by vincentarelbundock** [comment]
this is the main commit, with some cleaning up in a couple other ones after: https://github.com/vincentarelbundock/countrycode/commit/43eb3b4b79d77ecf0494b99500bbea66211fc2d1

**Comment by NilsEnevoldsen** [comment]
Thanks. This simplifies the codelist/panel sequencing.

The bad news is that this doesn't solve the original issue. If you do `s/^Afghanistan,afghan/Afghanistan,junk/`, then build, then filter the codelist for `country.name.en=='Afghanistan'`, you'll see that data for Afghanistan isn't merged in.

**Comment by vincentarelbundock** [comment]
Can you try again with the new updates? This time, please:

1. Modify `dictionary/data_regex.csv` (static has disappeared) and make sure you use a regex that should actually pick up the word (`junk` was a bad regex for Afghanistan).
2. Run `dictionary/build.R`

The main issue was that the build script was loading datasets from backup instead of scraping them from the web. That backup included pre-converted regexes for each dataset, so your changes weren't getting updated there.

The new build system is much simpler and (I think) better. We store two files for each datset:

1. `get_*.R` is used to scrape, and it saves a CSV file to the repo. We should only run this as needed, when we think that the original source has made changes to our codes.
2. `data_*.csv` must include a column called `country`.

When you run `build.R`, we convert the `country` column of each dataset to a regex, and use the regex to merge everything. There are sanity checks and tests.

**Comment by NilsEnevoldsen** [comment]
I forgot to leave a comment here. Yes, this works now. Thanks. I'm happy to have this issue closed if you are.
