### ISSUE TITLE
Error in the latest version of the package? 

### ISSUE THREAD

**Issue by skuchukh** [vincentarelbundock/countrycode#357]
Hello

I  installed countrycode on my newest Amazon AWS EC2 instance, and the I'm getting an error message in `countrycode::countrycode(c('Kenya', 'Zimbabwe'), origin = "country.name", destination = "iso3c")` : 
`Error in FUN(newX[, i], ...) : unused argument (simplify = FALSE)`
even though the code was working perfectly fine before on my machine. 

I  was wondering if you have any thoughts?
thank you!
Best
Salome

**Comment by vincentarelbundock** [comment]
This bug affects older R versions. It is fixed in the development version, but the fix has not been released to CRAN yet. 

You can install from GitHub in the meantime.

**Comment by skuchukh** [comment]
thanks for your quick response. in fact, I  installed it now via `install_github('vincentarelbundock/countrycode')`
but the issue persists.... thoughts? many many thanks1

**Comment by vincentarelbundock** [comment]
Did you restart your R session?

**Comment by skuchukh** [comment]
Whoops... this worked! apologies! Thank you for this amazing package

S
